### ISSUE TITLE
Jukebox do not play

### ISSUE THREAD

**Issue by Creepercdn** [MoonflowerTeam/etched#21]
It only display Now Playing, no error and no log.
Here is a generated crash log:
[Pastebin](https://pastebin.com/ETd58Qd4)

**Comment by Ocelot5836** [comment]
Can you provide the `latest.log`, and if on Forge the `debug.log` files?

**Comment by rsp4jack** [comment]
[debug.log](https://github.com/MoonflowerTeam/etched/files/7775439/debug.log)
[latest.log](https://github.com/MoonflowerTeam/etched/files/7775440/latest.log)

**Comment by jacksonhardaway** [comment]
These logs seem to show a crash from another mod. Could you test this with just etched installed and see it the problem occurs?

If it does, provide the latest.log and debug.log from the session.

**Comment by rsp4jack** [comment]
`net.minecraft.crash.ReportedException: Manually triggered debug crash`
The crash is manually triggered.
And I test it with only etched installed, and it works!

**Comment by rsp4jack** [comment]
This problem is not caused by Calcium, CCL, magnesium, roadrunner or sulfuric.

**Comment by jacksonhardaway** [comment]
The issue seems to be the URL is invalid, it's returning an HTML page. Double check the URL is actually directing to a download for a music file. Could you share the URL you used?

```
[1112月2021 15:35:21.623] [Downloader 5/ERROR] [me.jaackson.etched.common.menu.EtchingMenu/]: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.19.6</center>
</body>
</html>
```

**Comment by rsp4jack** [comment]
I use localhost address. and it is before I test it. When I input a valid URL, it does not log anything.

**Comment by rsp4jack** [comment]
and i see the music is downloaded. so, the problem is in playing.

**Comment by jacksonhardaway** [comment]
The URL you're using is returning a 404 page. Valid URLs will not log anything because they're valid, but they need to be accessible by the clients.

Is your server hosted on the same machine as the client?

**Comment by rsp4jack** [comment]
Yes.
Ignore the 404 error. That is an error URL and I really know it, so I inputted a valid URL after that. And it downloaded, but does not play.

**Comment by jacksonhardaway** [comment]
Can you share the URL you're using? Would like to replicate the issue

**Comment by rsp4jack** [comment]
I just use a nginx server in my PC and set root to my music folder (use alias in nginx config).

**Comment by rsp4jack** [comment]
I can see music is truly downloaded in etched-sounds.

**Comment by jacksonhardaway** [comment]
Without any URL to test, we can't replicate the issue. Try uploading the file somewhere else instead of localhost.

**Comment by rsp4jack** [comment]
https://github.com/Creepercdn/largefiles/raw/master/Kevin%20MacLeod%20-%20Barroom%20Ballet.mp3

**Comment by jacksonhardaway** [comment]
That seems to work fine, what happens when you use that URL?

**Comment by rsp4jack** [comment]
URL has no problem. The problem is It can't play any sound, but show "Now Playing" and no log or errors.

**Comment by jacksonhardaway** [comment]
I'm unable to replicate the issue using that URL. The music plays fine and displays everything correctly. If you can find which mod is causing Etched to be unable to play, I can take a look and fix it.

**Comment by rsp4jack** [comment]
do not know why, but the problem fix.
