### ISSUE TITLE
Etched Crashing my Game

### ISSUE THREAD

**Issue by PandaFalcon21** [MoonflowerTeam/etched#6]
Before Etched is put in my mods folder, everything is fine. But the second etched is added to my mods folder, I get a crash upon startup.

Logs: https://mcpaste.io/dd5b30cbf3481d27

Mods list:
![image](https://user-images.githubusercontent.com/26393263/123693278-dabad900-d825-11eb-9028-ed8234d9e7b6.png)

**Comment by PandaFalcon21** [comment]
I am having an identical issue with the mod 'Mannequins' that you also made.

**Comment by MuhannadYT** [comment]
This seemed to be becuase of optifabric and optifine

**Comment by PandaFalcon21** [comment]
But why is it only broken _after_ I add etched.

**Comment by jaacksondev** [comment]
OptiFine patches the method we're mixing into which is causing it to crash. Will look into it.

**Comment by PandaFalcon21** [comment]
Ok. Thank you so much

**Comment by ChaosDogG** [comment]
what i see is that there's two instances of the moobloom mod, both Forge and Fabric will scream if a mod is in the mods folder twice

**Comment by PandaFalcon21** [comment]
Hi ChaosDogG, those are actually two separate moobloom mods. One adds the ones from Minecraft Earth and one adds ones for each different type of flower and stuff.

**Comment by PandaFalcon21** [comment]
Has this been fixed yet?

**Comment by PandaFalcon21** [comment]
That shouldn't affect it. Before installing etched, it booted up perfectly without removing the duplicate

**Comment by PandaFalcon21** [comment]
That shouldn't affect it. Before installing etched, it booted up perfectly without removing the duplicate. In fact, I removed the duplicate and booted with etched and it crashed! https://mcpaste.io/a10ce206208627a1

**Comment by PandaFalcon21** [comment]
I'm going to assume this is yet to be fixed?

**Comment by jaacksondev** [comment]
I haven't had time, sorry. I highly recommend you don't use optifabric though as it's widely unsupported.
