### ISSUE TITLE
Jukebox doesn't stop playing.

### ISSUE THREAD

**Issue by COLDW0LF** [MoonflowerTeam/etched#8]
Hi there. Love the mod!

I had an issue just now where the jukebox wouldn't stop playing the Soundcloud link I put in.
Removing and re-adding the disc set a second iteration of the song playing, rinse, repeat etc.

After quitting out of the game with 18 billion copies of the song still playing, I can no longer load the world.
I can't provide a log unfortunately, because the game fails to load the world past recipe registration, and CTDs.

There's no concern about losing the save, it's a testing backup for modpack development...
I just thought I'd better give you a heads up, incase you can reproduce the issue!

I'm not using Optifine, Sodium etc, and the mod was working perfectly the last time I used Etched, pre 1.1.0.
If you need any more diagnostics, please let me know and I'll help where I can... assuming I can load the world!

**Comment by Ocelot5836** [comment]
I'll keep my eye on it and see if anyone else can reproduce

**Comment by Ocelot5836** [comment]
This issue seems to be fixed
